logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG
server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password:
    url: jdbc:mysql://localhost:3306/mobilelele2022?createDatabaseIfNotExist=true
    username: root
  jpa:
    #the next line is for reading of sql file, this property will say to
    #Spring to initializeted fir the data Base and after her initialization to
    # execute the sql file
      defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

#        for loading a data from data.sql file shoud use next propurties:
  #but first we need to unlock this JPA property - defer-datasource-initialization: true
  sql:
    init:
      mode: always

  #property for delete method

  mvc:
    hiddenmethod:
      filter:
        enabled: true
