logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG
server:
  port: 8000
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 6460okokok
    url: jdbc:mysql://localhost:3306/mobilelele2022?createDatabaseIfNotExist=true
    username: root
  jpa:
    #               the next line is for reading of sql file
    #        defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

        #property for delete method

  mvc:
    hiddenmethod:
      filter:
        enabled: true
